---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vk-host-opencode-config
  namespace: {{ .Values.namespace.name }}
data:
  opencode.json: |
    {{- .Files.Get "files/opencode.json" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vk-host-install-script
  namespace: {{ .Values.namespace.name }}
data:
  install-tools.sh: |
    {{- .Files.Get "files/install-tools.sh" | nindent 4 }}
