---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vk-db-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    app: vk-db
spec:
  storageClassName: {{ .Values.postgres.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vk-electric-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    app: vk-electric
spec:
  storageClassName: {{ .Values.electric.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.electric.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vk-host-workspace-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    app: vk-host
spec:
  storageClassName: {{ .Values.host.workspace.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.host.workspace.persistence.size }}
