---
apiVersion: v1
kind: Service
metadata:
  name: vk-remote-svc
  namespace: {{ .Values.namespace.name }}
  labels:
    app: vk-remote
spec:
  selector:
    app: vk-remote
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.remote.service.port }}
      targetPort: 8081
      {{- if eq .Values.remote.service.type "NodePort" }}
      nodePort: {{ .Values.remote.service.nodePort }}
      {{- end }}
  type: {{ .Values.remote.service.type }}
